inverters:
  - enabled: true
    host: 10.0.2.10
    port: 8000
    datalog: BA31101550
    serial: 3192670065
    heartbeats: false
    read_timeout: 300s
    short_read: 30s
    long_read: -1s
    health_check_duration: 3m


mqtt:
  enabled: true
  host: 10.0.13.40
  port: 1883
  clientName: LXP_Bridge_mqtt_client
  username:
  password:
  namespace: lxp
  publish_individual_input: false
  homeassistant:
    enabled: true
    prefix: homeassistant
statsd:
  server: ""
openEVSE:
  enabled: true
  topic: "lxp/sensor/BA31101550/read/power1"
  SOCChargeStart: 96
  SOCChargeMax: 98
  chargeStopValue: 1700
  chargeMaxValue: -400
